services:
  api:
    build:
      context: ..
      dockerfile: docker/fastapi.Dockerfile
    container_name: licitacao_api
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - ../.env
    volumes:
      - ..:/app
    depends_on:
      - postgres
      - ollama
    environment:
      DATABASE_URL: ${DATABASE_URL}

  dashboard:
    build:
      context: ..
      dockerfile: docker/streamlit.Dockerfile
    container_name: licitacao_dashboard
    ports:
      - "${DASHBOARD_PORT:-8501}:8501"
    env_file:
      - ../.env
    volumes:
      - ..:/app
    depends_on:
      - api

  postgres:
    image: postgres:15
    container_name: licitacao_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: licitacoes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/schemas.sql:/docker-entrypoint-initdb.d/schemas.sql

  ollama:
    image: ollama/ollama
    container_name: licitacao_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  ollama_data:
